CREATE DATABASE IF NOT EXISTS garment_db;
USE garment_db;

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  esp_id VARCHAR(50) NOT NULL,
  column_no INT NOT NULL,
  machine_no INT NOT NULL,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
